apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-with-labels-1
  labels:
    name: demo
    project: A
    env: stg
spec:
  containers:
  - image: hailsayan/k8s-demo-app:v1
    name: app
    ports:
    - containerPort: 8080
      protocol: TCP
